### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by kclim2** [viscloud/saf#1]
ubuntu@ubuntu-OptiPlex-7050:~/saf/docker/saf$ sudo docker build -f Dockerfile . -t saf --build-arg USE_VDMS=ON
Sending build context to Docker daemon  14.34kB
Step 1/66 : FROM ubuntu:16.04
 ---> b9e15a5d1e1a
Step 2/66 : MAINTAINER Shao-Wen Yang <shao-wen.yang@intel.com>
 ---> Using cache
 ---> a0d83aff6a6f
Step 3/66 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> edd61ebcfc69
Step 4/66 : ARG DEFAULT_WORKDIR=/vcs
 ---> Using cache
 ---> ab0ae059f8b4
Step 5/66 : ARG USE_VDMS=OFF
 ---> Using cache
 ---> 35c343c368e6
Step 6/66 : ARG GITHUB_URL=github.com/viscloud/saf.git
 ---> Using cache
 ---> 54840fd85491
Step 7/66 : ARG GITHUB_TOKEN=
 ---> Using cache
 ---> 0d7ce4c0b807
Step 8/66 : ARG SAF_HASH=
 ---> Using cache
 ---> f5548607c55f
Step 9/66 : RUN apt-get update
 ---> Using cache
 ---> b4669ce1018a
Step 10/66 : RUN apt-get install --yes dialog apt-utils
 ---> Running in e8c78b586011
Reading package lists...
Building dependency tree...
Reading state information...
Package dialog is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package apt-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dialog' has no installation candidate
E: Package 'apt-utils' has no installation candidate
The command '/bin/sh -c apt-get install --yes dialog apt-utils' returned a non-zero code: 100

ubuntu@ubuntu-OptiPlex-7050:~/saf/docker/saf$ uname -a
Linux ubuntu-OptiPlex-7050 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ccanel** [comment]
@kclim2 Just to gather more information, what version of docker and Ubuntu are are you using?

**Comment by ccanel** [comment]
This problem did not present for me on a fully-updated Ubuntu 16.04.5 with Docker version 17.03.2-ce, build f5ec1e2.

**Comment by syang100** [comment]
It doesn't seem to me from the log the Docker daemon is connected to the Internet? I am able to build on Ubuntu 16.04.3, 16.04.4 and MacOS High Sierra. On my MacBook, the Docker version is 18.06.1-ce-mac73 (26764). In case you are using the Docker from apt, use this instead -- https://docs.docker.com/install/linux/docker-ce/ubuntu/ .

**Comment by kclim2** [comment]
docker --version
Docker version 18.06.1-ce, build e68fc7a

uname -a
Linux ubuntu-OptiPlex-7050 4.14.20-041420-generic #201802162247 SMP Fri Feb 16 22:48:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

will check my docker internet connectivity and get back to you guys.

**Comment by kclim2** [comment]
latest: Pulling from library/ubuntu
124c757242f8: Pull complete
9d866f8bde2a: Pull complete
fa3f2f277e67: Pull complete
398d32b153e8: Pull complete
afde35469481: Pull complete
Digest: sha256:de774a3145f7ca4f0bd144c7d4ffb2931e06634f11529653b23eba85aef8e378
Status: Downloaded newer image for ubuntu:latest
ubuntu@ubuntu-OptiPlex-7050:~/saf/docker/saf$ sudo docker run -it ubuntu /bin/bash
root@74b4940983ed:/# apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [19.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [1363 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [211 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [80.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [74.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [414 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [242 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [4378 B]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [2807 B]
Fetched 25.9 MB in 10s (2655 kB/s)
Reading package lists... Done
root@74b4940983ed:/# apt-get install net-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 194 kB of archives.
After this operation, 803 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 net-tools amd64 1.60+git20161116.90da8a0-1ubuntu1 [194 kB]
Fetched 194 kB in 2s (116 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package net-tools.
(Reading database ... 4037 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60+git20161116.90da8a0-1ubuntu1_amd64.deb ...
Unpacking net-tools (1.60+git20161116.90da8a0-1ubuntu1) ...
Setting up net-tools (1.60+git20161116.90da8a0-1ubuntu1) ...

my computer seems fine with ubuntu docker container pulled from docker' library.

any advice for me to troubleshoot?

**Comment by ccanel** [comment]
@kclim2 Did you try manually installing docker like @syang100 suggested?

Perhaps it was a transient connectivity or repository problem. Any luck today?

**Comment by kclim2** [comment]
Yes, my docker was installed as per suggestion of @syang100 

still no luck with today.

**Comment by ccanel** [comment]
@kclim2 Please apply [this patch file](https://www.dropbox.com/s/f810j5e8b8pxp97/0001-Put-apt-update-on-same-line-as-apt-install.patch) and try again.

```sh
git apply 0001-Put-apt-update-on-same-line-as-apt-install.patch
```

**Comment by ccanel** [comment]
Also, try with the `--no-cache` option: `sudo docker build --no-cache --file ...`

**Comment by kclim2** [comment]
Yes, the apt-get update works and i can see packages are pulled from repository and installing success!.

Removing intermediate container cb8bdc093a0f
 ---> aaa92849bd81
Step 63/65 : RUN rm -f /usr/lib/x86_64-linux-gnu/libprotobuf*
 ---> Running in 770dd9ad8ee5
Removing intermediate container 770dd9ad8ee5
 ---> efff88d3d592
Step 64/65 : RUN apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in e301f8a4e733
Removing intermediate container e301f8a4e733
 ---> 16405c647eba
Step 65/65 : WORKDIR $DEFAULT_WORKDIR/saf
 ---> Running in 3a2d549e4719
Removing intermediate container 3a2d549e4719
 ---> 1d6cec4ece11
Successfully built 1d6cec4ece11
Successfully tagged saf:latest

ubuntu@ubuntu-OptiPlex-7050:~/saf/docker/saf$ sudo docker run -it saf /bin/sh
# ls
3rdparty	LICENSE    build   docker    run_detector.sh  run_visualizer.sh  src
AUTHORS		README.md  cmake   examples  run_simple.sh    run_writer.sh	 test
CMakeLists.txt	apps	   config  patches   run_tracker.sh   scripts

# ls /opt/intel	
computer_vision_sdk		intel_sdp_products.db	   ism
computer_vision_sdk_2018.1.265	intel_sdp_products.tgz.db  opencl
