### ISSUE TITLE
Is there any introduction about saf?

### ISSUE THREAD

**Issue by Janezzliu** [viscloud/saf#13]
Is there any article or paper about saf?I need to read the code by the some articles.

**Comment by ccanel** [comment]
We have not written a paper about SAF specifically, but it is used to implement the FilterForward system in [_Scaling Video Analytics on Constrained Edge Nodes_](https://arxiv.org/abs/1905.13536) from [SysML 2019](https://www.sysml.cc).

I also recommend looking at our [examples](https://github.com/viscloud/saf/tree/master/examples).

If you have a specific question, then please open another Issue and I will answer it.
