### ISSUE TITLE
saf build fail with tensorflow r1.5

### ISSUE THREAD

**Issue by kclim2** [viscloud/saf#2]
git checkout r1.5
./configure
bazel build --config=monolithic --config=opt //tensorflow:libtensorflow_cc.so
INFO: Elapsed time: 1072.685s, Critical Path: 104.34s
INFO: 2625 processes: 2625 local.
INFO: Build completed successfully, 2710 total actions

tensorflow r1.5 compiled success and i then proceed with saf build.

[ 51%] Built target dlib
Scanning dependencies of target saf
[ 51%] Building CXX object src/CMakeFiles/saf.dir/model/model_manager.cpp.o
[ 51%] Building CXX object src/CMakeFiles/saf.dir/operator/strider.cpp.o
[ 51%] Building CXX object src/CMakeFiles/saf.dir/operator/rtsp_sender.cpp.o
[ 53%] Building CXX object src/CMakeFiles/saf.dir/operator/image_transformer.cpp.o
[ 53%] Building CXX object src/CMakeFiles/saf.dir/operator/receivers/receiver.cpp.o
[ 55%] Building CXX object src/CMakeFiles/saf.dir/operator/senders/sender.cpp.o
[ 58%] Building CXX object src/CMakeFiles/saf.dir/operator/temporal_region_selector.cpp.o
[ 58%] Building CXX object src/CMakeFiles/saf.dir/operator/binary_file_writer.cpp.o
In file included from /home/ubuntu/tensorflow/tensorflow/core/public/session.h:22:0,
                 from /home/ubuntu/saf/src/model/tf_model.h:23,
                 from /home/ubuntu/saf/src/model/model_manager.cpp:27:
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/ubuntu/tensorflow/tensorflow/core/public/session.h:22:0,
                 from /home/ubuntu/saf/src/model/tf_model.h:23,
                 from /home/ubuntu/saf/src/model/model_manager.cpp:27:
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
src/CMakeFiles/saf.dir/build.make:123: recipe for target 'src/CMakeFiles/saf.dir/model/model_manager.cpp.o' failed
make[2]: *** [src/CMakeFiles/saf.dir/model/model_manager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/saf.dir/all' failed
make[1]: *** [src/CMakeFiles/saf.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

both the tensorflow latest branch and r1.5 break my saf build. any tips to fix this?

**Comment by ccanel** [comment]
@kclim2 It appears that your user-installed Protobuf is an older version than the one Google uses in TensorFlow r1.5. What version of Protobuf do you have installed?

Also, check out [the TensorFlow page](https://github.com/viscloud/saf/wiki/Building:-TensorFlow-Support) on the SAF wiki.

**Comment by kclim2** [comment]
i managed to follow the provided instruction to get saf build
https://github.com/viscloud/saf/wiki/Building:-SAF-on-OpenVINO-(aka-CVSDK)

this is the protobuf that is installed
git clone https://github.com/google/protobuf.git
cd protobuf
git reset --hard 513b35dc4e732a5649d50b2c56405109def40624

i then rebuild the tensorflow and proceed to recompile saf with tensorflow support
cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CVSDK=ON -DBACKEND=cpu -DUSE_SSD=ON -DUSE_WEBSOCKET=ON -DUSE_KAFKA=ON -DUSE_MQTT=ON -DUSE_PYTHON=ON -DTENSORFLOW_HOME=/home/ubuntu/tensorflow ..

this is the latest error

> [

 79%] Building CXX object src/CMakeFiles/saf.dir/operator/trackers/object_tracker.cpp.o
[ 79%] Building CXX object src/CMakeFiles/saf.dir/operator/neural_net_evaluator.cpp.o
In file included from /home/ubuntu/tensorflow/tensorflow/core/public/session.h:22:0,
                 from /home/ubuntu/saf/src/model/tf_model.h:23,
                 from /home/ubuntu/saf/src/model/model_manager.cpp:27:
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/ubuntu/tensorflow/tensorflow/core/public/session.h:23:0,
                 from /home/ubuntu/saf/src/model/tf_model.h:23,
                 from /home/ubuntu/saf/src/model/model_manager.cpp:27:
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/graph.pb.h:32:0,
                 from /home/ubuntu/tensorflow/tensorflow/core/public/session.h:23,
                 from /home/ubuntu/saf/src/model/tf_model.h:23,
                 from /home/ubuntu/saf/src/model/model_manager.cpp:27:
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/node_def.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/node_def.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/node_def.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.

**Comment by ccanel** [comment]
@kclim2 There is a version mismatch between the Protobuf you installed yourself and the one TensorFlow uses. [This page](https://github.com/viscloud/saf/wiki/Building:-TensorFlow-Support) explains how to fix it.

**Comment by ccanel** [comment]
@kclim2 Thank you for trying to use SAF and submitting Issues. It's nice to see someone interested in it.

**Comment by kclim2** [comment]
The tensorflow build error message reported https://github.com/viscloud/saf/issues/2#issuecomment-421513040 is produced after applying "Optional Step 1. Re-Generate TensorFlow Protobufs".

Should i try Optional Step 2?

Just to mention, the Protobuf was installed based on OpenVINO build instruction https://github.com/viscloud/saf/wiki/Building:-SAF-on-OpenVINO-(aka-CVSDK)

**Comment by ccanel** [comment]
Would you please report line 11 of `/home/ubuntu/tensorflow/bazel-genfiles/tensorflow/core/framework/device_attributes.pb.h`?

Also, please do `protoc --version`.

**Comment by kclim2** [comment]
#if GOOGLE_PROTOBUF_VERSION < 3004000

ubuntu@ubuntu-OptiPlex-7050:~/tensorflow$ protoc --version
libprotoc 3.5.1

**Comment by ccanel** [comment]
When you performed "Optional Step 1", were you in the `/home/ubuntu/tensorflow/` directory?

**Comment by kclim2** [comment]
> When you performed "Optional Step 1", were you in the `/home/ubuntu/tensorflow/` directory?

Yes. I was running Step 1 in the /home/ubuntu/tensorflow/ directory

Anyway, I'm building the docker now. Will apply Step 1 again and rebuild tensorflow.

**Comment by ccanel** [comment]
When you rerun "Optional Step 1", please post the output.

**Comment by kclim2** [comment]
finally everything successfully build!

ubuntu@ubuntu-OptiPlex-7050:~/tensorflow$ cat script.sh 
protofiles=`find tensorflow -type f -name "*.proto"`

rm -rf bazel-genfiles/tensorflow/

for protofile in ${protofiles[@]}; do
    echo $protofile
    protoc $protofile  --cpp_out=./bazel-genfiles/
done

ubuntu@ubuntu-OptiPlex-7050:~/tensorflow$ ./script.sh 
tensorflow/core/util/saved_tensor_slice.proto
tensorflow/core/util/memmapped_file_system.proto
tensorflow/core/util/example_proto_fast_parsing_test.proto
tensorflow/core/util/event.proto
tensorflow/core/util/test_log.proto
tensorflow/core/profiler/tfprof_output.proto
tensorflow/core/profiler/tfprof_options.proto
tensorflow/core/profiler/tfprof_log.proto
tensorflow/core/profiler/profile.proto
tensorflow/core/example/example_parser_configuration.proto
tensorflow/core/example/example.proto
tensorflow/core/example/feature.proto
tensorflow/core/protobuf/rewriter_config.proto
tensorflow/core/protobuf/debug.proto
tensorflow/core/protobuf/saved_model.proto
tensorflow/core/protobuf/worker_service.proto
tensorflow/core/protobuf/config.proto
tensorflow/core/protobuf/master_service.proto
tensorflow/core/protobuf/device_properties.proto
tensorflow/core/protobuf/tensor_bundle.proto
tensorflow/core/protobuf/saver.proto
tensorflow/core/protobuf/meta_graph.proto
tensorflow/core/protobuf/control_flow.proto
tensorflow/core/protobuf/tensorflow_server.proto
tensorflow/core/protobuf/master.proto
tensorflow/core/protobuf/worker.proto
tensorflow/core/protobuf/cluster.proto
tensorflow/core/protobuf/named_tensor.proto
tensorflow/core/protobuf/queue_runner.proto
tensorflow/core/grappler/costs/op_performance_data.proto
tensorflow/core/framework/versions.proto
tensorflow/core/framework/op_gen_overrides.proto
tensorflow/core/framework/allocation_description.proto
tensorflow/core/framework/node_def.proto
tensorflow/core/framework/step_stats.proto
tensorflow/core/framework/api_def.proto
tensorflow/core/framework/iterator.proto
tensorflow/core/framework/variable.proto
tensorflow/core/framework/types.proto
tensorflow/core/framework/log_memory.proto
tensorflow/core/framework/kernel_def.proto
tensorflow/core/framework/tensor_description.proto
tensorflow/core/framework/cost_graph.proto
tensorflow/core/framework/tensor_shape.proto
tensorflow/core/framework/tensor_slice.proto
tensorflow/core/framework/graph.proto
tensorflow/core/framework/resource_handle.proto
tensorflow/core/framework/function.proto
tensorflow/core/framework/tensor.proto
tensorflow/core/framework/reader_base.proto
tensorflow/core/framework/graph_transfer_info.proto
tensorflow/core/framework/op_def.proto
tensorflow/core/framework/device_attributes.proto
tensorflow/core/framework/remote_fused_graph_execute_info.proto
tensorflow/core/framework/attr_value.proto
tensorflow/core/framework/summary.proto
tensorflow/core/lib/core/error_codes.proto
tensorflow/core/debug/debug_service.proto
tensorflow/core/debug/debugger_event_metadata.proto
tensorflow/compiler/tf2xla/tf2xla.proto
tensorflow/compiler/xla/service/session.proto
tensorflow/compiler/xla/service/hlo.proto
tensorflow/compiler/xla/xla_data.proto
tensorflow/compiler/xla/xla.proto
tensorflow/python/util/protobuf/compare_test.proto
tensorflow/python/training/checkpoint_state.proto
tensorflow/python/framework/cpp_shape_inference.proto
tensorflow/contrib/gdr/gdr.proto
tensorflow/contrib/eager/proto/checkpointable_object_graph.proto
tensorflow/contrib/cloud/kernels/bigquery_table_partition.proto
tensorflow/contrib/session_bundle/manifest.proto
tensorflow/contrib/training/python/training/hparam.proto
tensorflow/contrib/boosted_trees/proto/quantiles.proto
tensorflow/contrib/boosted_trees/proto/learner.proto
tensorflow/contrib/boosted_trees/proto/split_info.proto
tensorflow/contrib/boosted_trees/proto/tree_config.proto
tensorflow/contrib/tensor_forest/proto/fertile_stats.proto
tensorflow/contrib/tensor_forest/proto/tensor_forest_params.proto
tensorflow/contrib/verbs/verbs_service.proto
tensorflow/contrib/decision_trees/proto/generic_tree_model_extensions.proto
tensorflow/contrib/decision_trees/proto/generic_tree_model.proto
tensorflow/contrib/tpu/profiler/tpu_profiler.proto
tensorflow/contrib/tpu/profiler/op_profile.proto
tensorflow/contrib/tpu/profiler/tf_op_stats.proto
tensorflow/contrib/tpu/profiler/trace_events.proto
tensorflow/contrib/tpu/proto/topology.proto
tensorflow/contrib/tensorboard/plugins/projector/projector_config.proto
tensorflow/contrib/tensorboard/plugins/trace/trace_info.proto
tensorflow/contrib/tensorboard/graph_explorer/proto/graph_explorer.proto
tensorflow/contrib/mpi/mpi_msg.proto
tensorflow/contrib/mpi_collectives/mpi_message.proto
tensorflow/contrib/lite/toco/model_flags.proto
tensorflow/contrib/lite/toco/types.proto
tensorflow/contrib/lite/toco/toco_flags.proto
tensorflow/tools/proto_text/test.proto
tensorflow/tools/api/lib/api_objects.proto

ubuntu@ubuntu-OptiPlex-7050:~/tensorflow$ bazel build --config=monolithic --config=opt //tensorflow:libtensorflow_cc.so
Starting local Bazel server and connecting to it...
WARNING: /home/ubuntu/tensorflow/tensorflow/core/BUILD:1814:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/ubuntu/tensorflow/tensorflow/tensorflow.bzl:1138:30
INFO: Analysed target //tensorflow:libtensorflow_cc.so (71 packages loaded).
INFO: Found 1 target...
INFO: From ProtoCompile tensorflow/contrib/cloud/kernels/bigquery_table_partition.pb.cc:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From ProtoCompile tensorflow/core/grappler/costs/op_performance_data.pb.cc:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
INFO: From ProtoCompile tensorflow/core/example/example.pb.cc:
bazel-out/k8-opt/genfiles/external/protobuf_archive/src: warning: directory does not exist.
Target //tensorflow:libtensorflow_cc.so up-to-date:
  bazel-bin/tensorflow/libtensorflow_cc.so
INFO: Elapsed time: 42.196s, Critical Path: 3.58s
INFO: 25 processes: 25 local.
INFO: Build completed successfully, 26 total actions

ubuntu@ubuntu-OptiPlex-7050:~/saf/cvsdk$ cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CVSDK=ON -DBACKEND=cpu -DUSE_SSD=ON -DUSE_WEBSOCKET=ON -DUSE_KAFKA=ON -DUSE_MQTT=ON -DUSE_PYTHON=ON -DTENSORFLOW_HOME=/home/ubuntu/tensorflow ..
-- Found OpenCV: /opt/intel/computer_vision_sdk_2018.3.343/opencv (found suitable version "3.4.3", minimum required is "3.0") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   graph
--   filesystem
--   iostreams
--   serialization
--   system
--   thread
--   regex
--   chrono
--   atomic
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.12") 
-- Disabling Caffe SSD because not using Intel Caffe!
-- C++11 activated.
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found OpenBLAS library
-- Using OpenBLAS's built in LAPACK
-- Checking for module 'libsasl2'
--   No package 'libsasl2' found
-- MySQL not found.
-- PostgreSQL not found.
-- Checking for module 'sqlite3'
--   No package 'sqlite3' found
-- Could NOT find SQLITE3 (missing:  SQLITE3_LIBRARIES SQLITE3_INCLUDE_DIRS) 
-- OCILIB not found.
can not use sqlite3
can not use mysql
can not use ocilib
can not use postgres
EXPAT_LIBRARIES=/usr/lib/x86_64-linux-gnu/libexpat.so
EXPAT_INCLUDE_DIRS=/usr/include
EXPAT_DEFINITIONS=
-- Patching RTTR...
HEAD is now at e338d9a noexcept specifier in function signature does not work correctly for MSVC compiler (#145)
-- Patched RTTR
Project version: 0.9.6
-- Architecture: x64
-- Enabled: use of RTTI
-- using C++: 11
-- 
-- Finding 3rd party libs...
-- ===========================
-- Finished finding 3rd party libs!
-- Scanning rttr module.
-- ===========================
-- rttr directory included
-- Scanning rttr module finished!
-- 
-- Un-patching RTTR...
HEAD is now at e338d9a noexcept specifier in function signature does not work correctly for MSVC compiler (#145)
-- Un-patched RTTR
-- Found OpenCV: /opt/intel/computer_vision_sdk_2018.3.343/opencv (found version "3.4.3") found components:  core 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.12", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "2.7.12") 
-- Found PythonInterp: /usr/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable exact version "3.5.2") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py27
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Checking for module 'libgvc'
--   No package 'libgvc' found
-- 
-- ********************** SAF Configuration Summary **********************
-- General:
--   Git               :   a592adf-dirty
--   System            :   Linux
--   On Tegra          :   No
--   Compiler          :   /usr/bin/c++ (ver. 5.4.0)
--   Release CXX flags :   -O3 -DNDEBUG
--   Debug CXX flags   :   -g
--   Build type        :   Release
--   Build tests       :   No
-- 
-- Options:
--   BACKEND           :   cpu
--   USE_CVSDK         :   Yes
--   USE_CAFFE         :   No
--   USE_FRCNN         :   No
--   USE_ISAAC         :   No
--   USE_KAFKA         :   Yes
--   USE_MQTT          :   Yes
--   USE_NCS           :   No
--   USE_PTGRAY        :   No
--   USE_PYTHON        :   Yes
--   USE_RPC           :   No
--   USE_SSD           :   Yes
--   USE_TENSORFLOW    :   No
--   USE_WEBSOCKET     :   Yes
--   USE_VDMS          :   No
--   USE_VIMBA         :   No
-- 
-- Frameworks:
--   Caffe             :   No
--   TensorFlow        :   No
-- 
-- Dependencies:
--   Boost             :   Yes (ver. 1.58, /usr/lib/x86_64-linux-gnu/libboost_system.so)
--   OpenCV            :   Yes (ver. 3.4.3, /opt/intel/computer_vision_sdk_2018.3.343/opencv/include)
--   Eigen             :   Yes (ver. 3.2.92, /usr/include/eigen3)
--   GStreamer         :   Yes (ver. 1.8.3, gstapp-1.0;gstbase-1.0;gstreamer-1.0;gobject-2.0;glib-2.0)
--   glog              :   Yes (ver. 0.3.4, glog)
--   ZeroMQ            :   Yes (ver. 4.1.4, zmq)
--   VecLib            :   No
--   CUDA              :   No
--   Cnmem             :   No
--   OpenCL            :   No
--   Protobuf          :   Yes (ver. , NOTFOUND)
--   JeMalloc          :   Yes (/usr/lib/x86_64-linux-gnu/libjemalloc.so)
--   FlyCapture        :   No
--   Vimba             :   No
--   Python API        :   Yes
-- 
-- Install:
--  Install path : /home/ubuntu/saf/cvsdk/3rdparty/rttr/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/saf/cvsdk

ubuntu@ubuntu-OptiPlex-7050:~/saf/cvsdk$ make -j4
[ 25%] Built target rdkafka
[ 51%] Built target dlib
[ 53%] Built target pbcvt
[ 68%] Built target rttr_core
[ 68%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/ConfImpl.cpp.o
[ 68%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/ConsumerImpl.cpp.o
[ 68%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/HandleImpl.cpp.o
[ 68%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/KafkaConsumerImpl.cpp.o
[ 70%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/MessageImpl.cpp.o
[ 70%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/MetadataImpl.cpp.o
[ 70%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/ProducerImpl.cpp.o
[ 70%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/QueueImpl.cpp.o
[ 72%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/RdKafka.cpp.o
[ 72%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/TopicImpl.cpp.o
[ 72%] Building CXX object 3rdparty/librdkafka/src-cpp/CMakeFiles/rdkafka++.dir/TopicPartitionImpl.cpp.o
[ 72%] Linking CXX shared library librdkafka++.so
[ 72%] Built target rdkafka++
[ 74%] Linking CXX shared library libsaf.so
[ 97%] Built target saf
Scanning dependencies of target safpy
[100%] Linking CXX shared library safpy.so
[100%] Built target safpy

ubuntu@ubuntu-OptiPlex-7050:~/saf/cvsdk$ make apps -j4
[ 25%] Built target rdkafka
[ 29%] Built target rdkafka++
[ 54%] Built target dlib
[ 79%] Built target saf
[ 79%] Linking CXX executable cd_detector
[ 79%] Linking CXX executable subscribe
[ 79%] Linking CXX executable binary_file_writer
[ 79%] Linking CXX executable gige
[ 79%] Built target binary_file_writer
[ 81%] Built target cd_detector
[ 81%] Built target subscribe
[ 81%] Built target gige
[ 81%] Linking CXX executable frame_writer
[ 81%] Linking CXX executable visualizer
[ 81%] Linking CXX executable recorder
[ 81%] Linking CXX executable simple
[ 83%] Built target frame_writer
[ 83%] Built target recorder
[ 83%] Linking CXX executable detector
[ 85%] Built target simple
[ 85%] Built target visualizer
[ 85%] Linking CXX executable classifier
[ 85%] Linking CXX executable save_vishashes
[ 87%] Linking CXX executable tracker
[ 87%] Built target detector
[ 87%] Built target save_vishashes
[ 87%] Linking CXX executable flow_control
[ 87%] Built target classifier
[ 87%] Linking CXX executable segmentation
[ 87%] Linking CXX executable rtsp_sender
[ 87%] Built target tracker
[ 89%] Linking CXX executable writer
[ 89%] Built target flow_control
[ 89%] Built target segmentation
[ 89%] Linking CXX executable encoder
[ 91%] Built target rtsp_sender
[ 91%] Linking CXX executable benchmark
[ 93%] Linking CXX executable jpeg_writer
[ 93%] Built target writer
[ 93%] Linking CXX executable people
[ 95%] Built target encoder
[ 95%] Linking CXX executable pipeline
[ 95%] Built target jpeg_writer
[ 95%] Built target benchmark
[ 97%] Linking CXX executable publish
[100%] Built target people
[100%] Built target pipeline
[100%] Built target publish
[100%] Built target apps

ubuntu@ubuntu-OptiPlex-7050:~/saf/cvsdk$ sudo make install_python
[sudo] password for ubuntu: 
[  2%] Built target pbcvt
[ 27%] Built target rdkafka
[ 31%] Built target rdkafka++
[ 56%] Built target dlib
[ 81%] Built target saf
[ 95%] Built target rttr_core
[ 97%] Built target safpy
Scanning dependencies of target install_python
[100%] Safpy linked at /usr/lib/python2.7/dist-packages.
[100%] Built target install_python
