### ISSUE TITLE
Stream queue full when selecting first GPU (intel) to be the execution device

### ISSUE THREAD

**Issue by kclim2** [viscloud/saf#3]
ubuntu@ubuntu-OptiPlex-7050:~/saf$ cvsdk/apps/detector -c rtsp --device 0 --detector_type cvsdk-ssd -m person-detection-retail-0013 --detector_targets person --detector_confidence_threshold 0.1 -d
W0915 10:39:11.005597  6292 context.h:159] Using encoder x264enc instead of default from configuration
W0915 10:39:11.005789  6292 context.h:166] using decoder avdec_h264 instead of default from configuration
Run detection demo
W0915 10:39:11.006166  6292 camera_manager.cpp:107] Not built with PtGray FlyCapture SDK, camera: ptgray is not loaded
W0915 10:39:11.006191  6292 camera_manager.cpp:115] Not built with AlliedVision Vimba SDK, camera: vimba is not loaded
I0915 10:39:11.006381  6292 operator.cpp:92] Starting rtsp...
I0915 10:39:11.006412  6292 operator.cpp:92] Starting Throttler...
I0915 10:39:11.006430  6292 operator.cpp:92] Starting ObjectDetector...
I0915 10:39:11.006536  6294 gst_video_capture.cpp:279] Capture video pipeline: rtspsrc latency=0 location="rtsp://192.168.1.6:554/Streaming/Channels/1" ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! capsfilter caps=video/x-raw,format=(string)BGR ! appsink name=sink sync=true
I0915 10:39:11.006558  6296 cvsdk_base.cpp:34] InferenceEngine: 
	API version ............ 1.2
	Build .................. 13911
I0915 10:39:11.006572  6296 cvsdk_base.cpp:36] Loading plugin
I0915 10:39:11.011054  6296 cvsdk_base.cpp:61] OpenVINO plugin version: 
	API version ............ 1.2
	Build .................. cldnn/GEN_GPU_clDNN_ci-main_cldnn-main-03988_artifacts.zip
	Description ....... clDNNPlugin
I0915 10:39:11.018430  6294 gst_video_capture.cpp:285] GStreamer pipeline launched
I0915 10:39:11.309888  6294 gst_video_capture.cpp:373] Pipeline connected, video size: 1920x1080
I0915 10:39:11.309944  6294 gst_video_capture.cpp:374] Video caps: video/x-raw, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)0/1, format=(string)BGR
W0915 10:39:11.977855  6295 stream.cpp:151] Stream queue full. Dropping frame: 16
W0915 10:39:12.016669  6295 stream.cpp:151] Stream queue full. Dropping frame: 17
W0915 10:39:12.056174  6295 stream.cpp:151] Stream queue full. Dropping frame: 18
W0915 10:39:12.096135  6295 stream.cpp:151] Stream queue full. Dropping frame: 19
W0915 10:39:12.137199  6295 stream.cpp:151] Stream queue full. Dropping frame: 20
W0915 10:39:12.176890  6295 stream.cpp:151] Stream queue full. Dropping frame: 21
W0915 10:39:12.216143  6295 stream.cpp:151] Stream queue full. Dropping frame: 22
W0915 10:39:12.257129  6295 stream.cpp:151] Stream queue full. Dropping frame: 23
W0915 10:39:12.296762  6295 stream.cpp:151] Stream queue full. Dropping frame: 24

without --device 0 can run without any problem.

**Comment by syang100** [comment]
Does it drop frames indefinitely? OpenVINO on GPU or VPU may take seconds at the very beginning for runtime model conversion/optimization. If the issue remains, let me know your kernel version using `uname -a` and your CPU models using `cat /proc/cpuinfo | grep "model name"`.

**Comment by kclim2** [comment]
@syang100 you are right, the first 8 seconds (the frame rate of the camera is around 25fps) of the rtsp stream is struggling but after that it start to be able to perform the detection without queue full warning but on and off we still can see the frame is dropping.

W0915 11:54:26.437106  6921 stream.cpp:151] Stream queue full. Dropping frame: 189
W0915 11:54:26.476429  6921 stream.cpp:151] Stream queue full. Dropping frame: 190
W0915 11:54:26.529036  6921 stream.cpp:151] Stream queue full. Dropping frame: 191
W0915 11:54:26.562630  6921 stream.cpp:151] Stream queue full. Dropping frame: 192
W0915 11:54:26.597756  6921 stream.cpp:151] Stream queue full. Dropping frame: 193
W0915 11:54:26.649333  6921 stream.cpp:151] Stream queue full. Dropping frame: 194
I0915 11:54:26.677289  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 195
W0915 11:54:26.716606  6921 stream.cpp:151] Stream queue full. Dropping frame: 196
W0915 11:54:26.770166  6921 stream.cpp:151] Stream queue full. Dropping frame: 197
I0915 11:54:26.797819  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 198
W0915 11:54:26.844909  6921 stream.cpp:151] Stream queue full. Dropping frame: 199
W0915 11:54:26.879650  6921 stream.cpp:151] Stream queue full. Dropping frame: 200
W0915 11:54:26.929898  6921 stream.cpp:151] Stream queue full. Dropping frame: 201
I0915 11:54:26.957720  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 202
W0915 11:54:26.996174  6921 stream.cpp:151] Stream queue full. Dropping frame: 203
W0915 11:54:27.049743  6921 stream.cpp:151] Stream queue full. Dropping frame: 204
I0915 11:54:27.078083  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 205
W0915 11:54:27.116828  6921 stream.cpp:151] Stream queue full. Dropping frame: 206
W0915 11:54:27.170799  6921 stream.cpp:151] Stream queue full. Dropping frame: 207
I0915 11:54:27.180596  6922 cvsdk_ssd_detector.cpp:53] CVSDKSsdDetector initialized
I0915 11:54:27.203244  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 208
I0915 11:54:27.234066  6922 cvsdk_ssd_detector.cpp:118] Only 85 proposals found
I0915 11:54:27.235921  6922 object_detector.cpp:225] Object detection took 55.275 ms
I0915 11:54:27.289513  6922 cvsdk_ssd_detector.cpp:118] Only 82 proposals found
I0915 11:54:27.290237  6922 object_detector.cpp:225] Object detection took 54.125 ms
I0915 11:54:27.326926  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 211
I0915 11:54:27.346698  6922 cvsdk_ssd_detector.cpp:118] Only 83 proposals found
I0915 11:54:27.347435  6922 object_detector.cpp:225] Object detection took 57.115 ms
I0915 11:54:27.399181  6922 cvsdk_ssd_detector.cpp:118] Only 83 proposals found
I0915 11:54:27.399544  6922 object_detector.cpp:225] Object detection took 52.039 ms
I0915 11:54:27.443581  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 214
I0915 11:54:27.453964  6922 cvsdk_ssd_detector.cpp:118] Only 84 proposals found
I0915 11:54:27.454560  6922 object_detector.cpp:225] Object detection took 54.965 ms
I0915 11:54:27.507591  6922 cvsdk_ssd_detector.cpp:118] Only 84 proposals found
I0915 11:54:27.508298  6922 object_detector.cpp:225] Object detection took 53.685 ms
I0915 11:54:27.558902  6922 cvsdk_ssd_detector.cpp:118] Only 81 proposals found
I0915 11:54:27.559618  6922 object_detector.cpp:225] Object detection took 51.267 ms
I0915 11:54:27.563295  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 217
I0915 11:54:27.611959  6922 cvsdk_ssd_detector.cpp:118] Only 83 proposals found
I0915 11:54:27.612848  6922 object_detector.cpp:225] Object detection took 53.138 ms
I0915 11:54:27.662087  6922 cvsdk_ssd_detector.cpp:118] Only 82 proposals found
I0915 11:54:27.662457  6922 object_detector.cpp:225] Object detection took 49.546 ms
I0915 11:54:27.687623  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 220
I0915 11:54:27.718940  6922 cvsdk_ssd_detector.cpp:118] Only 83 proposals found
I0915 11:54:27.719678  6922 object_detector.cpp:225] Object detection took 57.167 ms
I0915 11:54:27.769197  6922 cvsdk_ssd_detector.cpp:118] Only 81 proposals found
I0915 11:54:27.769562  6922 object_detector.cpp:225] Object detection took 49.814 ms
I0915 11:54:27.803628  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 223
I0915 11:54:27.820646  6922 cvsdk_ssd_detector.cpp:118] Only 85 proposals found
I0915 11:54:27.821051  6922 object_detector.cpp:225] Object detection took 51.433 ms
I0915 11:54:27.870065  6922 cvsdk_ssd_detector.cpp:118] Only 77 proposals found
I0915 11:54:27.870370  6922 object_detector.cpp:225] Object detection took 49.242 ms
I0915 11:54:27.920454  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 226
I0915 11:54:27.921638  6922 cvsdk_ssd_detector.cpp:118] Only 82 proposals found
I0915 11:54:27.921936  6922 object_detector.cpp:225] Object detection took 51.515 ms
I0915 11:54:27.971905  6922 cvsdk_ssd_detector.cpp:118] Only 86 proposals found
I0915 11:54:27.972249  6922 object_detector.cpp:225] Object detection took 50.28 ms
I0915 11:54:28.021682  6922 cvsdk_ssd_detector.cpp:118] Only 84 proposals found
I0915 11:54:28.022091  6922 object_detector.cpp:225] Object detection took 49.816 ms
I0915 11:54:28.045123  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 229
I0915 11:54:28.078054  6922 cvsdk_ssd_detector.cpp:118] Only 82 proposals found
I0915 11:54:28.079907  6922 object_detector.cpp:225] Object detection took 57.759 ms
I0915 11:54:28.129251  6922 cvsdk_ssd_detector.cpp:118] Only 77 proposals found
I0915 11:54:28.130342  6922 object_detector.cpp:225] Object detection took 50.323 ms
I0915 11:54:28.164475  6921 throttler.cpp:60] Frame rate too high. Dropping frame: 232

ubuntu@ubuntu-OptiPlex-7050:~/saf$ uname -a
Linux ubuntu-OptiPlex-7050 4.14.20-041420-generic #201802162247 SMP Fri Feb 16 22:48:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ubuntu-OptiPlex-7050:~/saf$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
stepping	: 3
microcode	: 0xc2
cpu MHz		: 1600.071
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 6816.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
