### ISSUE TITLE
SAF docker not able to convert tensorflow model

### ISSUE THREAD

**Issue by kclim2** [viscloud/saf#5]
i tried to follow the openvino instruction from https://software.intel.com/en-us/articles/OpenVINO-Using-TensorFlow#inpage-nav-8 to convert the model with SAF docker but stuck as follow:

. /opt/intel/computer_vision_sdk/deployment_tools/model_optimizer/install_prerequisites/../venv/bin/activate
(venv) # mo_tf.py --input_model=./ssd_inception_v2_coco_2018_01_28/frozen_inference_graph.pb --tensorflow_use_custom_operations_config ./extensions/front/tf/ssd_v2_support.json --tensorflow_object_detection_api_pipeline_config ./ssd_inception_v2_coco_2018_01_28/pipeline.config  --reverse_input_channels        
usage: mo_tf.py [-h] [--input_model INPUT_MODEL] [--model_name MODEL_NAME]
                [--output_dir OUTPUT_DIR] [--input_shape INPUT_SHAPE]
                [--scale SCALE] [--reverse_input_channels]
                [--log_level {CRITICAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}]
                [--input INPUT] [--output OUTPUT] [--mean_values MEAN_VALUES]
                [--scale_values SCALE_VALUES]
                [--data_type {FP16,FP32,half,float}] [--disable_fusing]
                [--disable_gfusing] [--extensions EXTENSIONS] [--batch BATCH]
                [--version] [--input_model_is_text]
                [--offload_unsupported_operations_to_tf]
                [--tensorflow_subgraph_patterns TENSORFLOW_SUBGRAPH_PATTERNS]
                [--tensorflow_operation_patterns TENSORFLOW_OPERATION_PATTERNS]
                [--tensorflow_custom_operations_config_update TENSORFLOW_CUSTOM_OPERATIONS_CONFIG_UPDATE]
                [--tensorflow_use_custom_operations_config TENSORFLOW_USE_CUSTOM_OPERATIONS_CONFIG]
                [--tensorboard_logdir TENSORBOARD_LOGDIR]
mo_tf.py: error: unrecognized arguments: --tensorflow_object_detection_api_pipeline_config ./ssd_inception_v2_coco_2018_01_28/pipeline.config

should we discuss this issue here or Intel computer vision sdk forum?

**Comment by syang100** [comment]
This looks like API mismatch. SAF Dockerfile uses OpenVINO version 2018.1.265 which is probably different from the version the instructions are assuming. Please install the latest OpenVINO on a host and follow the instructions. At the same time, please send me the models you'd like to convert over email and I will find you the help you need from Intel. This issue is irrelevant to SAF. Please close.

**Comment by XixiangChen444** [comment]
> This looks like API mismatch. SAF Dockerfile uses OpenVINO version 2018.1.265 which is probably different from the version the instructions are assuming. Please install the latest OpenVINO on a host and follow the instructions. At the same time, please send me the models you'd like to convert over email and I will find you the help you need from Intel. This issue is irrelevant to SAF. Please close.

Hello, I encountered the similar problem mentioned above when using MobileNetV2+ssdlite which was transformed from openvino to self-training. Could you please send me your email for further communication? My email is czcxixiang@hotmail.com. Thanks so much!!!!
